### ISSUE TITLE
identityChange doesn't verify the user's password

### ISSUE THREAD

**Issue by Millenniunn** [feathersjs-ecosystem/feathers-authentication-management#171]
POST: http://localhost:3030/authManagement
`
{ 
    "action": "identityChange", 
    "value": { 
        "user": {"email": "aaa@live.com" }, 
        "password": "xxxxx", 
        "changes": {"email": "bbb@live.com"} 
    } 
}
`

Both HTTP and Feathers call have the same issue, whatever password I have put there, it will assume the password is correct and send the verification email directly, after I clicked the url in email, the id(email) will successfully get updated.

**Comment by claustres** [comment]
Pretty strange, as far as I can see the CI is still running fine, there is a [specific test](https://github.com/feathersjs-ecosystem/feathers-authentication-management/blob/master/test/identity-change.test.js#L125) on this.

**Comment by kisunull** [comment]
Just checked my code, I'm using "feathers-authentication-management-ts": "^2.1.2", not sure if this is the reason.
@MohammedFaragallah 

From my understanding, once I installed the feathers-authentication-management, I can use 
`this.feathers.service('authManagement').create(data);` or regular HTTP method to call identityChange right?
`{ "action": "identityChange", "value": { "user": {"email": "aaa@live.com" }, "password": "xxxxx", "changes": {"email": "bbb@live.com"} } }`

Both of them have some issue, I tried to hard code the password, then any password allows the method to send the email.

emmm not sure how can I @Mohammed Faragallah here

**Comment by claustres** [comment]
If your point is to use typescript please wait for this PR to be merged https://github.com/feathersjs-ecosystem/feathers-authentication-management/pull/164. @fratzinger is currently generating a pre-release.

**Comment by kisunull** [comment]
thx a lot! that's great, we gonna have an official ts version!
any ideal when is this going to release? because I'm currently developing a project base on it.

**Comment by fratzinger** [comment]
```
npm i feathers-authentication-management@4.0.0-pre.0
```
It's alive. It's an early version though! There shouldn't be breaking changes. Please make sure to check out https://feathers-a-m.netlify.app/ .
Please let me know how it goes.

**Comment by OnnoGabriel** [comment]
I just testet the `identityChange` action in an app using the latest version (v3.1.0) of f-a-m. And I cannot confirm the reported issue. The service throws the expected "Password is incorrect." error.

@Millenniunn, what version are you using?

**Comment by kisunull** [comment]
> I just testet the `identityChange` action in an app using the latest version (v3.1.0) of f-a-m. And I cannot confirm the reported issue. The service throws the expected "Password is incorrect." error.
> 
> @Millenniunn, what version are you using?

@OnnoGabriel Ya, im using the 3rd party ts version. going to try the pre-release version that @fratzinger just mentioned. 
Thanks all!



> ```
> npm i feathers-authentication-management@4.0.0-pre.0
> ```
> 
> 
>      
>   
> 
> It's alive. It's an early version though! There shouldn't be breaking changes. Please make sure to check out https://feathers-a-m.netlify.app/ .
> Please let me know how it goes.

Thank you! going to try this version!

**Comment by kisunull** [comment]
@fratzinger What's the proper way to export the notifier function with TS? I followed the .js instruction here but couldn't make it works.
https://feathers-a-m.netlify.app/getting-started.html#implementation-of-the-notifier-function


![QQ20220107-173424](https://user-images.githubusercontent.com/85661265/148616169-b191f5d3-6b6a-4bcc-8e51-4f5b85d5bf77.png)
![QQ20220107-173527](https://user-images.githubusercontent.com/85661265/148616174-0d661c46-f3e9-430f-bd65-23a715b59fde.png)
![QQ20220107-173623](https://user-images.githubusercontent.com/85661265/148616176-5b7ee092-5583-47b6-9a6d-afcb26ee2032.png)


Another question, just curious, what's the point to use feathers-mailer? since I need to install nodemailer or nodemailer-smtp-transport for the transport anyway, why don't I just use the nodemailer to do all the jobs?

**Comment by fratzinger** [comment]
Thanks for the good explanation and screenshots! Highly appreciated!
There where a few errors in the guide. I fixed it in https://github.com/feathersjs-ecosystem/feathers-authentication-management/pull/164/commits/8473dbe6038fed909e34e1c5ae6236031732ad3d
Please look closely at the changes and follow the changes.
Last thing I see is the difference between type `string` and `NotificationType` in:
`(type: NotificationType, user: User, notifierOptions?: any)`. It's in your first screenshot.

**Comment by fratzinger** [comment]
`feathers-mailer` vs. `nodemailer`. It's just a convenience level. I like to have all things in `app` at my fingertips. Wether it is `app.service(...)` or `app.get(...)`. There where times I thought: 
> Nah, I don't need this elsewhere in the app. Just a quick hack here
and weeks later I saw me repairing the hack and moving it to a separate service with [`disallow('external')`](https://hooks-common.feathersjs.com/hooks.html#disallow)

**Comment by kisunull** [comment]
@fratzinger  Thank you for the quick response!
it does solved the error on user.hooks.ts (image 3 from my last post), but still getting error on auth-management.service.ts page.

Also two questions, 

1. is TS: `import notifier from './notifier'` same as JS: `const notifier = require("./notifier");` ?
2. 1. is TS: `export default function (app: Application)` same as JS: `module.exports =` ?

not sure any of these may caused the issue.

![QQ20220107-181530](https://user-images.githubusercontent.com/85661265/148619132-f52bbcd3-8eaa-4d8a-85f3-70b317869e52.png)

**Comment by kisunull** [comment]
@fratzinger I also just tried to follow the example in your branch, also got the error here

![QQ20220107-184555](https://user-images.githubusercontent.com/85661265/148621055-2da31db7-17cd-4ff9-83dd-d549af0253fa.png)

**Comment by kisunull** [comment]
> `feathers-mailer` vs. `nodemailer`. It's just a convenience level. I like to have all things in `app` at my fingertips. Wether it is `app.service(...)` or `app.get(...)`. There where times I thought:
> 
> > Nah, I don't need this elsewhere in the app. Just a quick hack here
> 
> and weeks later I saw me repairing the hack and moving it to a separate service with [`disallow('external')`](https://hooks-common.feathersjs.com/hooks.html#disallow)

Isn't this same thing? I can also just use this `app.service("mailer")` method to send emails with nodemailer
`const email: Service<SendMailOptions> = app.service("mailer");
email.create(payload)
     .then(() => console.log("New ticket email sent successfully"))
     .catch(console.error)
`


![QQ20220107-185912](https://user-images.githubusercontent.com/85661265/148621928-45a0937d-8161-4aa1-b0fc-5eaf84414387.png)
![QQ20220107-185946](https://user-images.githubusercontent.com/85661265/148621930-8a988d96-de74-4484-8ba1-764e255e5925.png)
![QQ20220107-185957](https://user-images.githubusercontent.com/85661265/148621932-fcae724b-0091-4a04-879f-5c5f6e392360.png)

**Comment by kisunull** [comment]
@fratzinger I have finally figured it out..
I changed `export default function (app: Application)` to `module.exports = (app: Application) =>` in notifier.ts
and `import notifier from './notifier'` to `const notifier = require("./notifier");` in auth-management.service.ts

![QQ20220107-235343](https://user-images.githubusercontent.com/85661265/148632220-111c6255-3ae0-40e7-a2d5-e5772d611d4c.png)
![QQ20220107-235417](https://user-images.githubusercontent.com/85661265/148632221-2a0e79f0-d793-4caa-9f4a-4c6abbb312a1.png)


But Im still curious why... isn't `module.exports ` a JS method? what should be the proper way to write it? I have tried all those but didn't work.

![QQ20220108-000410](https://user-images.githubusercontent.com/85661265/148632288-a07ddcb3-257d-426e-a04d-7870f5e5fe8b.png)




One more thing... I didn't realize it should be `addVerification("auth-management")` in the users.hook, cost me some time to debug.
This is weird since the regular JS branch doesn't need the `"auth-management"` and your `removeVerification()` also doesn't need it...

**Comment by fratzinger** [comment]
That's weird. But it has nothing todo with `feathers-authentication-management`, I think. Do you have other `export default` code in your code base that is working?

Please try the following:

```ts
// notifier.ts
export const notifier = (app: Application) => {
```

```ts
// auth-management.service.ts
import { notifier } from './notifier'
```

**Comment by fratzinger** [comment]
About `"auth-management"` in `addVerification`:
In v3 the recommended/default path of `f-a-m` was: `/authManagement`. `addVerification` uses this as default.

I wanted to change the `camelCase` to `kebab-case` because this feels more natural. But I don't want to break the migration from v3 to v4. New people coming to `f-a-m` just copy&paste the code from the docs and don't realize this.

**Comment by kisunull** [comment]
> That's weird. But it has nothing todo with `feathers-authentication-management`, I think. Do you have other `export default` code in your code base that is working?
> 
> Please try the following:
> 
> ```ts
> // notifier.ts
> export const notifier = (app: Application) => {
> ```
> 
> ```ts
> // auth-management.service.ts
> import { notifier } from './notifier'
> ```

I have tried that before, not working as well.
![WX20220108-121334](https://user-images.githubusercontent.com/85661265/148653416-a36a1015-6e71-41b6-8a45-472fd209958b.png)



> About `"auth-management"` in `addVerification`: In v3 the recommended/default path of `f-a-m` was: `/authManagement`. `addVerification` uses this as default.
> 
> I wanted to change the `camelCase` to `kebab-case` because this feels more natural. But I don't want to break the migration from v3 to v4. New people coming to `f-a-m` just copy&paste the code from the docs and don't realize this.

Thank you for the explanation!

And the identityChange issue is solved, thank you all. You may want to close the issue ticket anytime.
